export enum Actions {
  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  GET_PRODUCTS = "GET_PRODUCTS",
  GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT",
}
